enc_key: !!binary |
  R0NpSVoyb1VPejRZbl9vVFFVa2Zyblg3ZXl1VlZ0czZFUEdYMTh5aHJEST0=
etherscan_key: !!binary |
  Z0FBQUFBQmxMVEdQUi1DSDd0Um5mdkN6cDFJZS16N19YZ2QyNkJtQTVmT1VVaXQtSmpyTDFWVGhK
  YUQxSl9yVGhlUXJ6X3IzN09NZ282eFdtWVNsZXRjRUYwYlN5SmlBTWdsNnNTMTJrVGtLSEpaMmRE
  VjJaeUg4d1RtREM4M0R0aVhtelJUdlFIalE=
github_username: !!binary |
  Z0FBQUFBQmxMVElDSll5WnhkczAyLWlpcExia1l2RGZfRENaVjg2QmdYMWpkOTBIemtMRm03OFJU
  ZjFweTRJOW5fZHpNeWhvYlllak00OVpaQnVfR21GOThWRlA1alRud1E9PQ==
